"""Provider selection, request forwarding, and fallback logic."""

from __future__ import annotations

import asyncio
import gzip
import json
import logging
import zlib
from typing import TYPE_CHECKING

import aiohttp
from aiohttp import web

from .health import HealthRegistry
from .providers import Provider

if TYPE_CHECKING:
    pass

log = logging.getLogger(__name__)

# Module-level forced mode; "auto" means chain order + health checks.
_mode: str = "auto"


def get_mode() -> str:
    return _mode


def set_mode(mode: str, valid_names: set[str]) -> None:
    global _mode
    if mode != "auto" and mode not in valid_names:
        raise ValueError(f"Unknown provider: {mode!r}")
    _mode = mode


def pick_provider(model: str, providers: list[Provider],
                  registry: HealthRegistry,
                  tried: set[str] | None = None) -> Provider | None:
    tried = tried or set()
    if _mode != "auto":
        for p in providers:
            if p.name == _mode and p.name not in tried:
                if p.is_ready and p.supports_model(model) and registry.is_healthy(p.name):
                    return p
        return None

    for p in sorted(providers, key=lambda x: x.priority):
        if p.name in tried:
            continue
        if p.is_ready and p.supports_model(model) and registry.is_healthy(p.name):
            return p
    return None


def _encode_sse_event(event_line: str | None, data: dict) -> bytes:
    parts = []
    if event_line:
        parts.append(event_line)
    parts.append(f"data: {json.dumps(data)}")
    return "\n".join(parts).encode() + b"\n\n"


def _transform_sse_event(raw: bytes, in_thinking: bool) -> tuple[bool, list[bytes]]:
    """Rewrite thinking-block SSE events as text-block events.

    Returns (new_in_thinking, list of event byte chunks to emit).
    Thinking blocks from non-Anthropic providers carry invalid signatures;
    converting them to text blocks preserves the content without triggering
    Anthropic's signature validation on future turns.
    """
    event_str = raw.decode("utf-8", errors="replace")

    event_line = None
    data_str = None
    for line in event_str.split("\n"):
        if line.startswith("event:"):
            event_line = line
        elif line.startswith("data:"):
            data_str = line[5:].strip()

    if not data_str or data_str == "[DONE]":
        return in_thinking, [raw + b"\n\n"]

    try:
        data = json.loads(data_str)
    except json.JSONDecodeError:
        return in_thinking, [raw + b"\n\n"]

    event_type = data.get("type")

    if event_type == "content_block_start":
        cb = data.get("content_block", {})
        if cb.get("type") == "thinking":
            data["content_block"] = {"type": "text", "text": ""}
            open_delta = {
                "type": "content_block_delta",
                "index": data.get("index", 0),
                "delta": {"type": "text_delta", "text": "<thinking>\n"},
            }
            return True, [
                _encode_sse_event(event_line, data),
                _encode_sse_event("event: content_block_delta", open_delta),
            ]

    elif event_type == "content_block_delta" and in_thinking:
        delta = data.get("delta", {})
        if delta.get("type") == "thinking_delta":
            data["delta"] = {"type": "text_delta", "text": delta.get("thinking", "")}
            return True, [_encode_sse_event(event_line, data)]

    elif event_type == "content_block_stop" and in_thinking:
        close_delta = {
            "type": "content_block_delta",
            "index": data.get("index", 0),
            "delta": {"type": "text_delta", "text": "\n</thinking>"},
        }
        return False, [
            _encode_sse_event("event: content_block_delta", close_delta),
            raw + b"\n\n",
        ]

    return in_thinking, [raw + b"\n\n"]


def _is_thinking_signature_error(body: dict) -> bool:
    err = body.get("error", {})
    return (
        err.get("type") == "invalid_request_error"
        and "Invalid signature in thinking block" in err.get("message", "")
    )


def _sterilize_thinking_in_messages(body: dict) -> dict:
    """Convert thinking blocks in message history to text blocks.

    Called when Anthropic rejects a request due to invalid thinking signatures
    (e.g. blocks generated by a non-Anthropic provider in a previous turn).
    """
    new_messages = []
    for msg in body.get("messages", []):
        content = msg.get("content", [])
        if not isinstance(content, list):
            new_messages.append(msg)
            continue
        new_content = []
        for block in content:
            if isinstance(block, dict) and block.get("type") == "thinking":
                new_content.append({
                    "type": "text",
                    "text": f"<thinking>\n{block.get('thinking', '')}\n</thinking>",
                })
            else:
                new_content.append(block)
        new_messages.append({**msg, "content": new_content})
    return {**body, "messages": new_messages}


async def _stream(upstream: aiohttp.ClientResponse, response: web.StreamResponse,
                  sterilize: bool) -> None:
    if not sterilize:
        async for chunk in upstream.content.iter_any():
            await response.write(chunk)
        return

    in_thinking = False
    buf = b""
    async for chunk in upstream.content.iter_any():
        buf += chunk
        while b"\n\n" in buf:
            raw_event, buf = buf.split(b"\n\n", 1)
            in_thinking, events = _transform_sse_event(raw_event, in_thinking)
            for evt in events:
                await response.write(evt)
    if buf:
        await response.write(buf)


async def handle_proxy(request: web.Request) -> web.StreamResponse:
    providers: list[Provider] = request.app["providers"]
    registry: HealthRegistry = request.app["health_registry"]
    session: aiohttp.ClientSession = request.app["client_session"]

    raw_body = await request.read()
    try:
        body = json.loads(raw_body)
    except json.JSONDecodeError:
        body = {}

    requested_model: str = body.get("model", "")
    tried: set[str] = set()
    signature_sterilized = False  # only sterilize once per request

    while True:
        provider = pick_provider(requested_model, providers, registry, tried)
        if provider is None:
            tried_str = ", ".join(tried) if tried else "none"
            return web.Response(
                status=503,
                content_type="application/json",
                body=json.dumps({
                    "error": {
                        "type": "provider_unavailable",
                        "message": (
                            f"No healthy provider available for model {requested_model!r} "
                            f"(mode={_mode!r}, tried={tried_str})."
                        ),
                    }
                }),
            )

        upstream_url = provider.base_url + request.path_qs
        mutated = {**provider.extra_body, **body}
        mutated["model"] = provider.translate_model(requested_model)
        upstream_body = json.dumps(mutated).encode()

        headers = provider.apply_auth(dict(request.headers))
        headers.pop("Host", None)
        headers.pop("host", None)
        headers["Content-Length"] = str(len(upstream_body))

        log.info("→ %s %s via %s (model: %s → %s)",
                 request.method, request.path, provider.name,
                 requested_model, mutated["model"])

        try:
            upstream = await session.request(
                request.method,
                upstream_url,
                headers=headers,
                data=upstream_body,
                allow_redirects=False,
            )
        except (aiohttp.ClientConnectionError, asyncio.TimeoutError) as e:
            log.warning("Provider %s connection error: %s — trying next", provider.name, e)
            registry.record(provider.name, False, str(e))
            tried.add(provider.name)
            continue

        if upstream.status in (429, 529):
            log.warning("Provider %s returned %d — trying next", provider.name, upstream.status)
            registry.record(provider.name, False, f"{upstream.status}")
            tried.add(provider.name)
            upstream.release()
            continue

        if upstream.status == 400 and provider.native_thinking and not signature_sterilized:
            error_bytes = await upstream.read()
            resp_headers = {k: v for k, v in upstream.headers.items()
                            if k.lower() not in ("transfer-encoding", "content-length")}
            upstream.release()
            # Decompress a copy for inspection only; error_bytes stays as-is so the
            # forwarded body matches the pass-through Content-Encoding header.
            inspect_bytes = error_bytes
            if error_bytes.startswith(b"\x1f\x8b"):
                try:
                    inspect_bytes = gzip.decompress(error_bytes)
                except (gzip.BadGzipFile, zlib.error, EOFError):
                    inspect_bytes = b""
            try:
                error_body = json.loads(inspect_bytes)
            except (json.JSONDecodeError, UnicodeDecodeError):
                error_body = {}
            if _is_thinking_signature_error(error_body):
                log.warning("Thinking signature error — sterilizing history and retrying")
                body = _sterilize_thinking_in_messages(body)
                signature_sterilized = True
                continue  # retry same provider (not added to tried)
            return web.Response(status=400, headers=resp_headers, body=error_bytes)

        is_sse = "text/event-stream" in upstream.headers.get("Content-Type", "")
        sterilize = is_sse and not provider.native_thinking

        response = web.StreamResponse(
            status=upstream.status,
            headers={k: v for k, v in upstream.headers.items()
                     if k.lower() not in ("transfer-encoding", "content-length")},
        )
        await response.prepare(request)

        try:
            await _stream(upstream, response, sterilize)
        except (aiohttp.ClientError, ConnectionResetError) as e:
            log.debug("Stream closed from %s: %s", provider.name, e)
        finally:
            upstream.release()

        try:
            await response.write_eof()
        except (aiohttp.ClientError, ConnectionResetError):
            pass
        return response
